spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

pple:
  batch:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:13306/pple-assets-batch?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
      username: root
      password: root
      hikari:
        maximum-pool-size: 3
