spring:
  config:
    activate:
      on-profile: develop

pple:
  datasource:
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
    url: jdbc-secretsmanager:mysql://pple-assets-dev.cvp9gzbh38vp.ap-northeast-2.rds.amazonaws.com:3306/pple_assets?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: pple-assets-dev
