spring:
  config:
    activate:
      on-profile: develop

pple:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://pple-assets-dev.cvp9gzbh38vp.ap-northeast-2.rds.amazonaws.com:3306/pple-assets?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: root
