spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

springdoc:
  api-docs:
    enabled: false
  paths-to-match: /**/api/**
  swagger-ui:
    doc-expansion: none

management:
  metrics:
    tags:
      type: app
      role: ${ROLE:pple_assets}
      instance_id: ${INSTANCE_ID:unknown}
  trace:
    http:
      enabled: true
